---
- hosts: default
  vars:
    devstack_repo: git://github.com/openstack-dev/devstack.git
    public_ip: 192.168.27.100
    neutron: True
    swift: True
    security_groups: False

  tasks:
    - name: install packages
      apt: "pkg={{ item }} update_cache=yes"
      sudo: True
      with_items:
       - git

    - name: checkout devstack
      git: "repo={{ devstack_repo }} dest=/home/vagrant/devstack"

    - name: localrc
      template: src=templates/localrc dest=/home/vagrant/devstack/localrc

    - name: source openrc in profile
      lineinfile: dest=/home/vagrant/.profile regexp=".*openrc" line='. /home/vagrant/devstack/openrc'

    - name: enable eth2
      command: ip link set dev eth2 up
      sudo: True

